services:
    mongo:
        image: mongo:6.0
        container_name: rakstage_mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:7.0
        container_name: rakstage_redis
        restart: always
        ports:
            - "6379:6379"

volumes:
    mongo_data:
        driver: local
